[PE] fix has_relocations_ field
lief-project/LIEF pull request #900
Opened 2023-04-19 06:55 UTC by spobit

2023-04-19 08:40 UTC, romainthomas commented on src/PE/Binary.cpp
> +  this->has_relocations_ = this->relocations_.size();
I would prefer `.empty()` overs `.size()`

2023-04-19 08:40 UTC, romainthomas commented on src/PE/Binary.cpp
> +  this->has_relocations_ = this->relocations_.size();
Same

2023-04-19 08:41 UTC, romainthomas requested changes
cf. comments

2023-04-20 01:07 UTC, spobit commented on src/PE/Binary.cpp
> +  this->has_relocations_ = this->relocations_.size();
good idea

2023-04-21 12:23 UTC, romainthomas commented
Merged through 4ef1759bd484c37289675cf4d05862d924435f9f (I squashed the commits)

2023-04-21 12:23 UTC, closed without merging