feat(macho): allow to create DynamicSymbolCommand in Python
lief-project/LIEF pull request #924
Opened 2023-06-07 14:57 UTC by LouisBrunner

I created a static function (`createForPython`) to avoid messing with the implementation of the default constructor.

2023-06-09 03:43 UTC, romainthomas requested changes
I get the idea behinds this PR and I'll handle the integration in the next couple of days.

2023-06-09 03:43 UTC, romainthomas commented on include/LIEF/MachO/DynamicSymbolCommand.hpp
> +  static DynamicSymbolCommand createForPython();
Core header files should not expose Python specific function :)

2023-06-10 07:56 UTC, romainthomas commented
Let me know if 1a69a1b16bf7f15cf92a83da0f3584446b5a6f65 would be ok.

2023-06-17 11:50 UTC, romainthomas commented
ping @LouisBrunner

2023-06-21 12:27 UTC, LouisBrunner commented
Hey, sorry for the delay.

It's not possible for me to test running an actual binary without all the other changes for `MainCommand`, etc, however from `otool`'s output it looks like it's working.

2023-06-21 14:17 UTC, merged